
obj-$(CONFIG_LGE_BROADCAST)   += tcpal_debug.o
obj-$(CONFIG_LGE_BROADCAST)   += tcpal_queue.o
obj-$(CONFIG_LGE_BROADCAST)   += tcpal_linux.o
obj-$(CONFIG_LGE_BROADCAST)   += tcpal_io_cspi.o
obj-$(CONFIG_LGE_BROADCAST)   += tcpal_io_i2c.o
obj-$(CONFIG_LGE_BROADCAST)   += tcpal_irq_handler.o

EXTRA_CFLAGS += -Idrivers/broadcast/tcc3170/inc
EXTRA_CFLAGS += -Idrivers/broadcast/tcc3170/inc/tcpal
EXTRA_CFLAGS += -Idrivers/broadcast/tcc3170/inc/tcbd_stream_parser
EXTRA_CFLAGS += -Idrivers/broadcast/tcc3170/inc/tcbd_diagnosis
