--- drivers/broadcast/tdmb/Makefile	2012-12-31 06:33:44.000000000 +0900
+++ drivers/broadcast/tdmb/Makefile	2012-11-23 18:12:31.000000000 +0900
@@ -3,8 +3,7 @@
 #
 
 obj-$(CONFIG_LGE_BROADCAST_TDMB)		+= broadcast_tdmb_drv_if.o
-#obj-$(CONFIG_LGE_BROADCAST_TDMB)		+= fc8050/
+obj-$(CONFIG_LGE_BROADCAST_TDMB_FC8050)		+= fc8050/
 #obj-$(CONFIG_LGE_BROADCAST_TDMB)		+= lg2102/
 obj-$(CONFIG_LGE_BROADCAST_TDMB_T3900)		+= t3900/
 #obj-$(CONFIG_LGE_BROADCAST_TDMB_T39FX)		+= t39fx/
-obj-$(CONFIG_LGE_BROADCAST_TDMB_TCC3170)	+= tcc3170/