
obj-$(CONFIG_LGE_BROADCAST)   += tcbd_stream_parser.o

EXTRA_CFLAGS += -Idrivers/broadcast/tcc3170/inc
EXTRA_CFLAGS += -Idrivers/broadcast/tcc3170/inc/tcbd_stream_parser
EXTRA_CFLAGS += -Idrivers/broadcast/tcc3170/inc/tcpal
