obj-$(CONFIG_LGE_BROADCAST)   += tcbd_diagnosis.o

EXTRA_CFLAGS += -Idrivers/broadcast/tcc3170/inc
EXTRA_CFLAGS += -Idrivers/broadcast/tcc3170/inc/tcpal
EXTRA_CFLAGS += -Idrivers/broadcast/tcc3170/inc/tcbd_diagnosis
