#
# Makefile for TI's HCI IF driver, which sits above 
# WCG ST (shared transport) driver. It makes use 
# of shared transport line discipline core driver to
# communicate with the BT core of the combo chip.
#

obj-$(CONFIG_ST_HCI) 		+= hci_if_drv.o



