--- drivers/broadcast/tdmb/fc8050/Makefile	2012-12-31 06:33:44.000000000 +0900
+++ drivers/broadcast/tdmb/fc8050/Makefile	2012-11-23 18:12:31.000000000 +0900
@@ -4,5 +4,5 @@
 
 # Each configuration option enables a list of files.
 # LGE
-obj-$(CONFIG_LGE_BROADCAST_TDMB)	+= src/
+obj-$(CONFIG_LGE_BROADCAST_TDMB_FC8050)	+= src/
 #obj-y		+= src/
