obj-$(CONFIG_OMAP2_DSS) += omapdss.o
omapdss-y := core.o dss.o dispc.o display.o manager.o overlay.o wb.o
omapdss-$(CONFIG_OMAP2_DSS_DPI) += dpi.o
omapdss-$(CONFIG_OMAP2_DSS_RFBI) += rfbi.o
omapdss-$(CONFIG_OMAP2_DSS_VENC) += venc.o
omapdss-$(CONFIG_OMAP2_DSS_SDI) += sdi.o
omapdss-$(CONFIG_OMAP2_DSS_DSI) += dsi.o
#LGE_CHANGE [wonki.choi@lge.com] HDMI refactoring 2011-4-15 */
#omapdss-$(CONFIG_OMAP2_DSS_HDMI) += hdmi.o
omapdss-$(CONFIG_OMAP2_DSS_HDMI) += hdmi_cosmo.o
omapdss-$(CONFIG_OMAP2_DSS_HDMI) += edid.o
