obj-$(CONFIG_LGE_BROADCAST)   += tcbd_fic_decoder.o

EXTRA_CFLAGS += -Idrivers/broadcast/tcc3170/inc
EXTRA_CFLAGS += -Idrivers/broadcast/tcc3170/inc/tcbd_fic_decoder
EXTRA_CFLAGS += -Idrivers/broadcast/tcc3170/inc/tcpal
